<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "social_auth"
 *
 * Auto generated by Extension Builder 2015-09-22
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
    'title' => 'Social auth',
    'description' => 'Authentication via social auth (Facebook, Twitter, Google +, LinkedIn & Instagram)',
    'category' => 'plugin',
    'author' => 'VANCLOOSTER Mickael',
    'author_email' => 'vanclooster.mickael@gmail.com',
    'state' => 'stable',
    'internal' => '',
    'uploadfolder' => 0,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.2.6',
    'constraints' => array(
        'depends' => array(
            'typo3' => '9.5.0-9.5.99'
        ),
        'conflicts' => array(
        ),
        'suggests' => array(
        ),
    ),
);
