<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "social_auth"
 *
 * Auto generated by Extension Builder 2015-09-22
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Social auth',
	'description' => 'Authentification via social auth (Facebook, Twitter, Google + & LinkedIn)',
	'category' => 'plugin',
	'author' => 'VANCLOOSTER Mickael',
	'author_email' => 'vanclooster.mickael@gmail.com',
	'state' => 'beta',
	'internal' => '',
	'uploadfolder' => 0,
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '1.0.7',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2.0-7.6.99'
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);